---
#
# Ansible managed
#
repository:
  description: Install and configure owncloud on your system.
  homepage: https://buluma.github.io/
  topics: owncloud, ansible, molecule, tox, playbook, hacktoberfest
