---
image: "buluma/github-action-molecule:4.0.6"

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1

molecule:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
  retry: 1
  parallel:
    matrix:
      - image: "docker-ubuntu-systemd"
        tag: "focal"
      - image: "opensuse"
        tag: "latest"
      - image: "debian-systemd"
        tag: "bullseye"
      - image: "fedora-systemd"
        tag: "34"
      - image: "fedora-systemd"
        tag: "33"
      - image: "fedora-systemd"
        tag: "32"

testing:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "testing"
  retry: 1
  parallel:
    matrix:
      - image: "docker-ubuntu-systemd"
        tag: "focal"
      - image: "opensuse"
        tag: "latest"
      - image: "debian-systemd"
        tag: "bullseye"
      - image: "fedora-systemd"
        tag: "34"
      - image: "fedora-systemd"
        tag: "33"
      - image: "fedora-systemd"
        tag: "32"

galaxy:
  script:
    - ansible-galaxy role info buluma.owncloud

role_testing_live:
  script:
    - image=${image} tag=${tag} ansible-galaxy install buluma.owncloud
  retry: 1
  parallel:
    matrix:
      - image: "docker-ubuntu-systemd"
        tag: "focal"
      - image: "opensuse"
        tag: "latest"
      - image: "debian-systemd"
        tag: "bullseye"
      - image: "fedora-systemd"
        tag: "34"
      - image: "fedora-systemd"
        tag: "33"
      - image: "fedora-systemd"
        tag: "32"
