---
- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  delegate_to: localhost
  run_once: true

- name: Groupadd
  ansible.builtin.group:
    name: "{{ ocis_group }}"
    state: present
    system: true

- name: Useradd
  ansible.builtin.user:
    name: "{{ ocis_owner }}"
    group: "{{ ocis_group }}"
    home: "{{ ocis_data_path }}"
    create_home: false
    shell: "/usr/sbin/nologin"
    state: present
    system: true

- name: Prepare directories
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: "{{ ocis_owner }}"
    group: "{{ ocis_group }}"
    mode: "0750"
    state: directory
  loop:
    - "{{ ocis_config_dir }}"
    - "{{ ocis_data_path }}"

- name: Download oCIS binary
  ansible.builtin.get_url:
    url: "{{ ocis_download.url }}"
    dest: "{{ ocis_binary_path }}"
    checksum: "{{ ocis_download.checksum }}"
    owner: root
    group: root
    mode: "0755"

- name: Place ocis.env
  ansible.builtin.template:
    dest: "{{ ocis_config_dir }}/ocis.env"
    src: ocis.env.j2
    owner: "{{ ocis_owner }}"
    group: "{{ ocis_group }}"
    mode: "0640"

- name: Initialize oCIS configuration
  ansible.builtin.command:
    cmd: "{{ ocis_binary_path }} init --config-path {{ ocis_config_dir }}"
    creates: "{{ ocis_config_dir }}/ocis.yaml"
  become: true
  become_user: "{{ ocis_owner }}"
  environment:
    HOME: "{{ ocis_data_path }}"
    IDM_ADMIN_PASSWORD: "{{ ocis_admin_pass }}"
  no_log: true

- name: Place ocis.service
  ansible.builtin.template:
    dest: /etc/systemd/system/ocis.service
    src: ocis.service.j2
    owner: root
    group: root
    mode: "0644"
  notify:
    - Ocis | systemctl daemon-reload
    - Ocis | systemctl restart ocis

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Systemctl start ocis
  ansible.builtin.service:
    name: ocis
    state: started
    enabled: true
