---
- name: Verify
  hosts: all
  become: false
  gather_facts: true
  tasks:
    - ansible.builtin.command:
        cmd: /usr/bin/ocis version
      name: Run ocis version
      changed_when: false
    - ansible.builtin.uri:
        url: "https://{{ ansible_facts['default_ipv4'].address |
          default(ansible_facts['all_ipv4_addresses'][0]) }}:9200/"
        validate_certs: false
        status_code:
          - 200
          - 302
      name: Get oCIS web UI
      register: ocis_get_root
      retries: 30
      delay: 2
      until:
        - ocis_get_root is succeeded
